version: '3.7'
services:
  nfl-mock-draft-db:
    image: postgres
    restart: always
    volumes:
      - ./postgresql/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mockdraft
      POSTGRES_PASSWORD: mockdraft
      ANON: web_anon
      AUTHENTICATOR: authenticator
  nfl-mock-draft-redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local